# Setup
title:               Mutualism Ecology
tagline:             'Chris Moore'
description:         ''
url:                 https://mutualismecology.com
baseurl:
paginate:            3
permalink:           pretty

# About/contact
author:
  name:              Chris Moore
  url:
  email:             cmmoore@colby.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-68437941-1
