# Setup
title:               Mutualism Ecology
tagline:             'by Chris Moore'
description:         'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 https://mutualismecology.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Chris Moore
  url:               https://twitter.com/mdo
  email:             cmmoore@colby.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-68437941-1
